swagger: '2.0'
info:
  title: Playola Api
  description: Build and listen to internet radio stations.
  version: 1.0.0
host: api.playola.fm
schemes:
  - https
basePath: /api/v1
produces:
  - application/json
