swagger: '2.0'
info:
  title: Playola Api
  description: Move your app forward with the Uber API
  version: 1.0.0
host: api.playola.fm
schemes:
  - https
basePath: /api/v1
produces:
  - application/json
